/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.testesort;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 * 
 * Interface gráfica em SWT para os testes.
 * 
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }
    
    
    //Gera os teste e liga os resultados no HashMap aos labels na tela.
    private void geraTestes(Long tamanhoEntrada){
        Testes testes = new Testes();
        HashMap<String, String> resultados;
        
        resultados = testes.testaSort(tamanhoEntrada);
        
        cSRandom.setText(resultados.get("cSRandom"));
        qSRandom.setText(resultados.get("qSRandom"));
        qSMelhor.setText(resultados.get("qSMelhor"));
        qSPior.setText(resultados.get("qSPior"));
        hSRandom.setText(resultados.get("hSRandom"));
        hSMelhor.setText(resultados.get("hSMelhor"));
        mSRandom.setText(resultados.get("mSRandom"));
        mSMelhor.setText(resultados.get("mSMelhor"));
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cSRandom = new javax.swing.JLabel();
        qSRandom = new javax.swing.JLabel();
        qSPior = new javax.swing.JLabel();
        qSMelhor = new javax.swing.JLabel();
        hSRandom = new javax.swing.JLabel();
        hSMelhor = new javax.swing.JLabel();
        mSRandom = new javax.swing.JLabel();
        mSMelhor = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        tamanhoEntradaForm = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamanho da Entrada");

        jLabel2.setText("Collections.Sort");

        jLabel3.setText("QuickSort");

        jLabel5.setText("HeapSort");

        jLabel6.setText("Merge Sort");

        jLabel7.setText("Melhor Caso");

        jLabel8.setText("Pior Caso");

        jLabel9.setText("Random");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        cSRandom.setText("0");

        qSRandom.setText("0");

        qSPior.setText("0");

        qSMelhor.setText("0");

        hSRandom.setText("0");

        hSMelhor.setText("0");

        mSRandom.setText("0");

        mSMelhor.setText("0");

        jLabel24.setText("Status: ");

        status.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSRandom))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tamanhoEntradaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(qSMelhor)
                                        .addComponent(hSMelhor)
                                        .addComponent(mSMelhor)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(qSPior, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(qSRandom, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hSRandom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mSRandom, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(1, 1, 1)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tamanhoEntradaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(cSRandom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qSRandom)
                    .addComponent(qSPior)
                    .addComponent(qSMelhor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hSRandom)
                    .addComponent(hSMelhor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mSRandom)
                    .addComponent(mSMelhor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSair)
                        .addComponent(btnIniciar))
                    .addComponent(status))
                .addContainerGap())
        );

        jLabel10.getAccessibleContext().setAccessibleName("collectionSort");
        cSRandom.getAccessibleContext().setAccessibleName("collectionSort");
        qSRandom.getAccessibleContext().setAccessibleName("qSRandom");
        qSPior.getAccessibleContext().setAccessibleName("qSPior");
        qSMelhor.getAccessibleContext().setAccessibleName("qSMelhor");
        hSRandom.getAccessibleContext().setAccessibleName("hSRandom");
        hSMelhor.getAccessibleContext().setAccessibleName("hSMelhor");
        mSRandom.getAccessibleContext().setAccessibleName("mSRandom");
        mSMelhor.getAccessibleContext().setAccessibleName("mSMelhor");
        status.getAccessibleContext().setAccessibleName("status");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
                
        Long tamanhoEntrada = new Long(0);
        //Verifica se o valor da entrada é um número maior que 0
        try {
            tamanhoEntrada = Long.parseLong(tamanhoEntradaForm.getValue().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite somente números", "Erro de tipo de dados", JOptionPane.ERROR_MESSAGE);
        }
        
        if(tamanhoEntrada > 0){
            
            status.setText("Testando");
            geraTestes(tamanhoEntrada);
            status.setText("Terminado");
            
        } else {
            JOptionPane.showMessageDialog(this, "Digite um valor válido no campo", "Erro de validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel cSRandom;
    private javax.swing.JLabel hSMelhor;
    private javax.swing.JLabel hSRandom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mSMelhor;
    private javax.swing.JLabel mSRandom;
    private javax.swing.JLabel qSMelhor;
    private javax.swing.JLabel qSPior;
    private javax.swing.JLabel qSRandom;
    private javax.swing.JLabel status;
    private javax.swing.JSpinner tamanhoEntradaForm;
    // End of variables declaration//GEN-END:variables
}
